# Database Server Variables
# Uses standardized variable naming convention

# PostgreSQL Configuration
postgresql_version: "17"
postgresql_port: 5432
postgresql_listen_addresses: "localhost"
postgresql_max_connections: 100
postgresql_shared_buffers: "256MB"

# Database Users & Databases
postgresql_databases: []
  # - name: myapp
  #   owner: myapp_user
  #   encoding: UTF8
  #   lc_collate: en_US.UTF-8
  #   lc_ctype: en_US.UTF-8

postgresql_users: []
  # - name: myapp_user
  #   password: "{{ vault_db_password }}"
  #   role_attr_flags: CREATEDB,NOSUPERUSER
  #   database: myapp
  #   priv: ALL

# Redis Configuration (if on same server)
redis_port: 6379
redis_password: "{{ vault_redis_password | default('') }}"
redis_memory_mb: 256

# PostGIS Configuration
postgis_enabled: false
postgis_version: "3.4"

# Backward compatibility mappings
pg_version: "{{ postgresql_version }}"
pg_port: "{{ postgresql_port }}"
pg_databases: "{{ postgresql_databases }}"
pg_users: "{{ postgresql_users }}"