# Database Server Variables
# This file can override defaults for database servers

# PostgreSQL Databases to Create (define in host vars or vault)
postgresql_databases: []
  # - name: myapp
  #   owner: myapp_user
  #   encoding: UTF8
  #   lc_collate: en_US.UTF-8
  #   lc_ctype: en_US.UTF-8

# PostgreSQL Users to Create (define in host vars or vault)
postgresql_users: []
  # - name: myapp_user
  #   password: "{{ vault_db_password }}"
  #   role_attr_flags: CREATEDB,NOSUPERUSER
  #   database: myapp
  #   priv: ALL

# PostGIS Configuration
postgis_enabled: false