# Ansible Vault - Encrypted Credentials
# This file contains sensitive credentials and should be encrypted with ansible-vault
# 
# To encrypt this file, run:
# ansible-vault encrypt cloudy/inventory/group_vars/vault.yml
#
# To edit encrypted vault, run:
# ansible-vault edit cloudy/inventory/group_vars/vault.yml

# IMPORTANT: Replace these example values with your actual secure credentials
# before encrypting the vault file

# Root User Credentials (for initial server setup before SSH keys)
vault_root_password: "REPLACE_WITH_SECURE_ROOT_PASSWORD"

# Admin User Credentials (for ongoing admin operations)
vault_admin_password: "REPLACE_WITH_SECURE_ADMIN_PASSWORD"

# Database Credentials
vault_postgres_password: "REPLACE_WITH_SECURE_DATABASE_PASSWORD"
vault_mysql_root_password: "REPLACE_WITH_SECURE_MYSQL_PASSWORD"

# Cache Credentials
vault_redis_password: "REPLACE_WITH_SECURE_REDIS_PASSWORD"

# VPN Credentials
vault_vpn_passphrase: "REPLACE_WITH_SECURE_VPN_PASSPHRASE"