# Web Server Variables
# This file can override defaults for web servers

# Domain Configuration (usually set per host)
nginx_domain: "example.com"
nginx_server_aliases: []
  # - www.example.com
  # - api.example.com

# SSL Configuration
nginx_ssl_enabled: true
letsencrypt_enabled: false
letsencrypt_email: "admin@{{ nginx_domain }}"

# Supervisor Configuration
supervisor_enabled: false
supervisor_programs: []
  # - name: myapp
  #   command: /srv/www/myapp/venv/bin/gunicorn app:application
  #   directory: /srv/www/myapp
  #   user: www-data
  #   autostart: true
  #   autorestart: true

# PgBouncer Configuration (Connection Pooling)
pgbouncer_enabled: true

# Backend Database Connection (usually set per environment)
pgbouncer_backend_host: "pg.internal"  # Override per environment
