---
# cloudy/tasks/sys/security/kernel-hardening.yml
# Apply kernel security parameters for production

- name: Configure kernel security parameters
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  loop:
    # Kernel hardening
    - { name: 'kernel.randomize_va_space', value: '2' }
    - { name: 'kernel.kptr_restrict', value: '2' }
    - { name: 'kernel.dmesg_restrict', value: '1' }
    - { name: 'kernel.yama.ptrace_scope', value: '1' }
    - { name: 'fs.suid_dumpable', value: '0' }
    - { name: 'kernel.core_uses_pid', value: '1' }
    - { name: 'kernel.sysrq', value: '0' }
    - { name: 'kernel.panic', value: '60' }
    - { name: 'kernel.panic_on_oops', value: '1' }
    
    # Network security - IPv4
    - { name: 'net.ipv4.conf.all.rp_filter', value: '1' }
    - { name: 'net.ipv4.conf.default.rp_filter', value: '1' }
    - { name: 'net.ipv4.conf.all.accept_source_route', value: '0' }
    - { name: 'net.ipv4.conf.default.accept_source_route', value: '0' }
    - { name: 'net.ipv4.conf.all.send_redirects', value: '0' }
    - { name: 'net.ipv4.conf.default.send_redirects', value: '0' }
    - { name: 'net.ipv4.conf.all.accept_redirects', value: '0' }
    - { name: 'net.ipv4.conf.default.accept_redirects', value: '0' }
    - { name: 'net.ipv4.conf.all.secure_redirects', value: '0' }
    - { name: 'net.ipv4.conf.default.secure_redirects', value: '0' }
    - { name: 'net.ipv4.conf.all.log_martians', value: '1' }
    - { name: 'net.ipv4.conf.default.log_martians', value: '1' }
    - { name: 'net.ipv4.icmp_echo_ignore_broadcasts', value: '1' }
    - { name: 'net.ipv4.icmp_ignore_bogus_error_responses', value: '1' }
    
    # TCP hardening
    - { name: 'net.ipv4.tcp_syncookies', value: '1' }
    - { name: 'net.ipv4.tcp_rfc1337', value: '1' }
    - { name: 'net.ipv4.tcp_timestamps', value: '0' }
    - { name: 'net.ipv4.tcp_max_syn_backlog', value: '2048' }
    - { name: 'net.ipv4.tcp_synack_retries', value: '2' }
    - { name: 'net.ipv4.tcp_syn_retries', value: '5' }
    
    # Network security - IPv6
    - { name: 'net.ipv6.conf.all.accept_source_route', value: '0' }
    - { name: 'net.ipv6.conf.default.accept_source_route', value: '0' }
    - { name: 'net.ipv6.conf.all.accept_redirects', value: '0' }
    - { name: 'net.ipv6.conf.default.accept_redirects', value: '0' }
    - { name: 'net.ipv6.conf.all.forwarding', value: '0' }

- name: Create sysctl configuration file for persistence
  template:
    src: sysctl-security.conf.j2
    dest: /etc/sysctl.d/99-cloudy-security.conf
    owner: root
    group: root
    mode: '0644'

- name: Disable core dumps for setuid programs
  lineinfile:
    path: /etc/security/limits.conf
    line: "* hard core 0"
    create: yes

- name: Restrict kernel module loading
  copy:
    dest: /etc/modprobe.d/cloudy-blacklist.conf
    content: |
      # Disable rare network protocols
      install dccp /bin/true
      install sctp /bin/true
      install rds /bin/true
      install tipc /bin/true
      
      # Disable rare filesystems
      install cramfs /bin/true
      install freevxfs /bin/true
      install jffs2 /bin/true
      install hfs /bin/true
      install hfsplus /bin/true
      install squashfs /bin/true
      install udf /bin/true
      install vfat /bin/true
      
      # Disable firewire
      install firewire-core /bin/true
      install firewire-ohci /bin/true
      install firewire-sbp2 /bin/true
    owner: root
    group: root
    mode: '0644'