---
- name: Create system users
  ansible.builtin.user:
    name: "{{ item.name }}"
    uid: "{{ item.uid | default(omit) }}"
    group: "{{ item.group | default(item.name) }}"
    groups: "{{ item.groups | default([]) }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    home: "{{ item.home | default('/home/' + item.name) }}"
    create_home: "{{ item.create_home | default(true) }}"
    system: "{{ item.system | default(false) }}"
    state: "{{ item.state | default('present') }}"
  become: true
  loop: "{{ system_users | default([]) }}"
  tags: [system, users]

- name: Set up SSH keys for users
  ansible.posix.authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
    state: present
  become: true
  loop: "{{ system_users | default([]) | subelements('ssh_keys', skip_missing=true) }}"
  tags: [system, users, ssh]

- name: Configure sudo access
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/{{ item.name }}
    line: "{{ item.name }} ALL=(ALL) {{ 'NOPASSWD:' if item.sudo_nopasswd | default(false) else '' }}ALL"
    create: true
    validate: 'visudo -cf %s'
    mode: '0440'
  become: true
  loop: "{{ system_users | default([]) }}"
  when: item.sudo | default(false)
  tags: [system, users, sudo]