# Ansible-lint configuration for Ansible Cloudy
# More permissive settings for practical development

profile: basic  # Use basic profile instead of production

# Skip specific rules that are too strict for this project
skip_list:
  - yaml[trailing-spaces]      # Allow trailing spaces (handled by yamllint)
  - yaml[new-line-at-end-of-file]  # Allow missing newlines (handled by yamllint) 
  - fqcn[action-core]          # Allow short module names (include_tasks vs ansible.builtin.include_tasks)
  - var-naming[no-reserved]    # Allow some reserved variable names
  - jinja[spacing]             # Allow flexible jinja spacing
  - ignore-errors              # Allow ignore_errors when appropriate
  # Temporarily removed: deprecated-module to test if linting works

# Exclude paths we don't want to lint
exclude_paths:
  - cloudy/tasks/services/     # Third-party service tasks

# Use offline mode to avoid external dependencies
offline: true

# Enable specific useful rules
enable_list:
  - no-changed-when            # Ensure changed_when is used appropriately
  - no-tabs                    # Prevent tab characters