version: '3.8'

services:
  web-server:
    build: .
    image: ansible-cloudy/web-server:latest
    container_name: web-server
    hostname: webserver
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./html:/var/www/html
    ports:
      - "80:80"
      - "443:443"
      - "2223:22"
    networks:
      - cloudy-network
    restart: unless-stopped
    depends_on:
      - database

  database:
    image: postgres:15-alpine
    container_name: web-database
    environment:
      POSTGRES_DB: webapp
      POSTGRES_USER: webapp
      POSTGRES_PASSWORD: secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cloudy-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  cloudy-network:
    driver: bridge