---
# Task: Check SSH Connectivity
# Purpose: Verify SSH connection to target server before proceeding
# This provides clear error messages when connection fails

- name: Check SSH connectivity on configured port
  wait_for:
    host: "{{ ansible_host }}"
    port: "{{ vault_ssh_port | default(vault_ssh_port_default) }}"
    timeout: 10
    state: started
    msg: "Waiting for SSH on {{ ansible_host }}:{{ vault_ssh_port | default(vault_ssh_port_default) }}"
  delegate_to: localhost
  become: false
  register: ssh_check
  ignore_errors: true
  no_log: false

- name: Display connection failure message
  fail:
    msg: |
      ❌ Unable to connect to {{ ansible_user }}@{{ ansible_host }}:{{ vault_ssh_port | default(vault_ssh_port_default) }}
      
      This could mean:
      1. SSH port has changed - check your .vault/*.yml files
      2. Server is unreachable or down
      3. Firewall is blocking the connection
      
      Current vault_ssh_port: {{ vault_ssh_port | default(vault_ssh_port_default) }}
      
      If you recently changed the SSH port:
      1. Update vault_ssh_port in your .vault/*.yml file
      2. Or update ansible_port in your inventory file
      
      To test connection manually:
      ssh -p {{ vault_ssh_port | default(vault_ssh_port_default) }} {{ ansible_user }}@{{ ansible_host }}
  when: ssh_check.failed | default(false)

- name: Confirm SSH connectivity
  debug:
    msg: "✅ SSH connectivity confirmed on {{ ansible_host }}:{{ vault_ssh_port | default(vault_ssh_port_default) }}"
  when: not (ssh_check.failed | default(false))