---
- name: LAMP Stack Complete Recipe
  hosts: webservers
  become: true
  gather_facts: true
  
  vars:
    lamp_db_name: webapp
    lamp_db_user: webapp
    lamp_db_password: "{{ vault_lamp_db_password | default('changeme') }}"
  
  pre_tasks:
    - name: Validate required variables
      ansible.builtin.assert:
        that:
          - lamp_db_password is defined
          - lamp_db_password != "changeme"
        fail_msg: "Please set lamp_db_password in vault or group_vars"
  
  roles:
    # Baseline system setup
    - role: ../../roles/system/apt-update
      vars:
        apt_upgrade: true
    - role: ../../roles/system/timezone
    - role: ../../roles/system/users
    - role: ../../roles/security/ssh-hardening
    
    # Web server stack
    - role: ../../roles/services/nginx
    - role: ../../roles/services/postgresql
      vars:
        postgresql_databases:
          - name: "{{ lamp_db_name }}"
        postgresql_users:
          - name: "{{ lamp_db_user }}"
            password: "{{ lamp_db_password }}"
            priv: "{{ lamp_db_name }}.*:ALL"
    
    # Security and monitoring
    - role: ../../roles/security/firewall
      vars:
        firewall_rules:
          - { port: 80, protocol: tcp, rule: allow }
          - { port: 443, protocol: tcp, rule: allow }
          - { port: "{{ ssh_port | default(22) }}", protocol: tcp, rule: allow }
    
    - role: ../../roles/applications/backup
      vars:
        backup_targets:
          - type: postgresql
            databases: ["{{ lamp_db_name }}"]
          - type: files
            paths: ["/var/www/html"]
  
  post_tasks:
    - name: Create sample index page
      ansible.builtin.copy:
        content: |
          <?php
          phpinfo();
          ?>
        dest: /var/www/html/index.php
        owner: www-data
        group: www-data
        mode: '0644'
  
  tags: [lamp, complete-recipe]