# Staging Inventory - Production-like but separate environment
# Copy and customize for your staging environment

---
all:  
  vars:
    # === CONNECTION CONFIGURATIONS ===
    
    # Default connection (root with SSH keys - post-security)
    ansible_user: "{{ vault_root_user }}"
    ansible_port: "{{ vault_ssh_port }}"
    ansible_host_key_checking: "{{ vault_ansible_host_key_checking }}"
    ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"
    ansible_ssh_common_args: "{{ vault_ansible_ssh_common_args }}"
    
    # Global Settings (with vault fallbacks)
    git_user_full_name: "{{ vault_git_user_full_name }}"
    git_user_email: "{{ vault_git_user_email }}"
    timezone: "{{ vault_timezone }}"
    locale: "{{ vault_locale }}"
    
  children:
    # === CONNECTION SWITCHING GROUPS ===
    
    # Security setup group - uses root with password for initial setup
    security_targets:
      vars:
        ansible_user: "{{ vault_root_user }}"
        ansible_port: "{{ vault_ssh_port }}"
        ansible_ssh_pass: "{{ vault_root_password }}"  # Required for initial setup
        ansible_host_key_checking: "{{ vault_ansible_host_key_checking }}"
        ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"
        ansible_ssh_common_args: "{{ vault_ansible_ssh_common_args }}"
      hosts:
        # Include all staging servers for security setup
        staging-web: {}
        staging-db: {}
        staging-cache: {}
    
    # Post-security group - uses root with SSH keys for all operations  
    service_targets:
      vars:
        ansible_user: "{{ vault_root_user }}"
        ansible_port: "{{ vault_ssh_port }}"
        ansible_host_key_checking: "{{ vault_ansible_host_key_checking }}"
        ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"
        ansible_ssh_common_args: "{{ vault_ansible_ssh_common_args }}"
      hosts:
        # Include all staging servers for service operations
        staging-web: {}
        staging-db: {}
        staging-cache: {}
    
    # === SERVICE-SPECIFIC GROUPS ===
    
    # Web Application Servers
    web_servers:
      vars:
        admin_user: "{{ vault_grunt_user | default('admin') }}"
        admin_password: "{{ vault_grunt_password }}"  # Required if grunt user defined
        admin_groups: "admin,www-data"
        webserver: gunicorn
        webserver_port: 8181
        python_version: "3.11"
        geo_ip_enabled: true
        
      hosts:
        staging-web:
          ansible_host: 10.0.10.10
          hostname: staging-web.example.com
          domain_name: staging.example.com

    # Database Servers
    database_servers:
      vars:
        admin_user: "{{ vault_grunt_user | default('admin') }}"
        admin_password: "{{ vault_grunt_password }}"  # Required if grunt user defined
        admin_groups: "admin,www-data"
        postgresql_version: "15"
        postgis_version: "3.3"
        listen_address: "*"
        
      hosts:
        staging-db:
          ansible_host: 10.0.10.11
          hostname: staging-db.example.com
          database_port: 5432
          postgres_password: "{{ vault_postgres_password }}"  # Required

    # Cache Servers  
    cache_servers:
      vars:
        admin_user: "{{ vault_grunt_user | default('admin') }}"
        admin_password: "{{ vault_grunt_password }}"  # Required if grunt user defined
        admin_groups: "admin,www-data"
        redis_memory: 256  # MB - smaller for staging
        redis_interface: "0.0.0.0"
        
      hosts:
        staging-cache:
          ansible_host: 10.0.10.12
          hostname: staging-cache.example.com
          port: 6379
          password: "{{ vault_redis_password }}"  # Required