# Test Inventory for All Simplified Workflows
# Step 1: ansible-playbook -i inventory/dev.yml playbooks/recipes/core/security.yml 
# Step 2: ansible-playbook -i inventory/dev.yml playbooks/recipes/core/base.yml
# Step 3: ansible-playbook -i inventory/dev.yml playbooks/recipes/[category]/[service].yml
#
# NOTE: Vault variables can be loaded via: -e @.vault/my-dev.yml

---
all:
  vars:
    # Global Settings (with vault fallbacks)
    git_user_full_name: "{{ vault_git_user_full_name | default('System Administrator') }}"
    git_user_email: "{{ vault_git_user_email | default('admin@example.com') }}"
    timezone: "{{ vault_timezone | default('America/New_York') }}"
    locale: "{{ vault_locale | default('en_US.UTF-8') }}"
    
    # === CONNECTION CONFIGURATIONS ===
    
    # Default connection (root with SSH keys - for all operations)
    ansible_user: "{{ vault_ansible_user | default('root') }}"
    ansible_port: "{{ vault_ssh_port | default(22022) }}"
    ansible_host_key_checking: "{{ vault_ansible_host_key_checking | default(false) }}"
    ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file | default('~/.ssh/id_rsa') }}"
    ansible_ssh_common_args: "{{ vault_ansible_ssh_common_args | default('-o StrictHostKeyChecking=no') }}"
    
    # Security Configuration - Optional Grunt User Section
    # Only configured if vault_grunt_user is defined in vault
    # Services can optionally run under this user instead of root
    grunt_user: "{{ vault_grunt_user | default('') }}"
    grunt_password: "{{ vault_grunt_password | default('') }}"
    grunt_groups: "{{ vault_grunt_groups | default(admin_groups_default) }}"
    grunt_ssh_private_key_file: "{{ vault_grunt_ssh_private_key_file | default('~/.ssh/id_rsa') }}"
    
  # === GROUP VARIABLES FOR CONNECTION SWITCHING ===
  children:
    # Security setup group - uses root with password for initial setup
    security_targets:
      vars:
        ansible_user: "{{ vault_ansible_user | default('root') }}"
        ansible_port: "{{ vault_initial_ssh_port | default(22) }}"
        ansible_ssh_pass: "{{ vault_root_password }}"  # Required for initial setup, no default
        ansible_host_key_checking: "{{ vault_ansible_host_key_checking | default(false) }}"
        ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file | default('~/.ssh/id_rsa') }}"
        ansible_ssh_common_args: "{{ vault_ansible_ssh_common_args | default('-o StrictHostKeyChecking=no') }}"
      hosts:
        test-server: {}
    
    # Post-security group - uses root with SSH keys for all operations
    service_targets:
      vars:
        ansible_user: "{{ vault_ansible_user | default('root') }}"
        ansible_port: "{{ vault_ssh_port | default(22022) }}"
        ansible_host_key_checking: "{{ vault_ansible_host_key_checking | default(false) }}"
        ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file | default('~/.ssh/id_rsa') }}"
        ansible_ssh_common_args: "{{ vault_ansible_ssh_common_args | default('-o StrictHostKeyChecking=no') }}"
      hosts:
        test-server: {}

  hosts:
    # Main test server - used for all recipes
    test-server:
      ansible_host: 10.10.10.198
      hostname: test-server.example.com
      ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file | default('~/.ssh/id_rsa') }}"
      
      # PostgreSQL Databases to Create
      postgresql_databases:
        - name: myapp_db
          owner: myapp_user
          encoding: UTF8
          lc_collate: en_US.UTF-8
          lc_ctype: en_US.UTF-8
        - name: gis_db
          owner: gis_user
          encoding: UTF8
          lc_collate: en_US.UTF-8
          lc_ctype: en_US.UTF-8
      
      # PostgreSQL Users to Create
      postgresql_users:
        - name: myapp_user
          password: "{{ vault_postgres_password }}"  # Required, no default
          database: myapp_db
          priv: ALL
          role_attr_flags: CREATEDB,NOSUPERUSER
        - name: gis_user
          password: "{{ vault_postgres_password }}"  # Required, no default
          database: gis_db
          priv: ALL
          role_attr_flags: CREATEDB,NOSUPERUSER
        - name: readonly_user
          password: "{{ vault_postgres_password }}"  # Required, no default
          role_attr_flags: NOSUPERUSER
      
