# Test Inventory for All Simplified Workflows
# Step 1: ansible-playbook -i inventory/dev.yml playbooks/recipes/core/security.yml 
# Step 2: ansible-playbook -i inventory/dev.yml playbooks/recipes/core/base.yml
# Step 3: ansible-playbook -i inventory/dev.yml playbooks/recipes/[category]/[service].yml
#
# NOTE: Vault variables are loaded via group_vars/all/vault.yml (symlinked to .secrets/dev.yml)

---
all:
  vars:
    # Global Settings (with vault fallbacks)
    git_user_full_name: "{{ vault_git_user_full_name | default('John Doe') }}"
    git_user_email: "{{ vault_git_user_email | default('jdoe@example.com') }}"
    timezone: "{{ vault_timezone | default('America/New_York') }}"
    locale: "{{ vault_locale | default('en_US.UTF-8') }}"
    
    # === CONNECTION CONFIGURATIONS ===
    
    # Default connection (admin user with SSH keys - post-security)
    ansible_user: "{{ vault_admin_user }}"
    ansible_port: "{{ vault_ssh_port | default(22) }}"
    ansible_host_key_checking: false
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
    # Security Configuration - Admin User Section
    # All operations and services shall be run under this user
    # Cronjobs will also be run under this user
    admin_user: "{{ vault_admin_user }}"
    admin_password: "{{ vault_admin_password }}"  # For account creation only, not SSH
    admin_groups: "admin,www-data"
    admin_ssh_private_key_file: ~/.ssh/id_rsa
    
  # === GROUP VARIABLES FOR CONNECTION SWITCHING ===
  children:
    # Security setup group - uses root with password for initial setup
    security_targets:
      vars:
        ansible_user: root
        ansible_port: 22
        ansible_ssh_pass: "{{ vault_root_password }}"
        ansible_host_key_checking: false
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      hosts:
        test-server: {}
    
    # Post-security group - uses admin with SSH keys for all operations
    service_targets:
      vars:
        ansible_user: "{{ vault_admin_user }}"
        ansible_port: "{{ vault_ssh_port | default(22) }}"
        ansible_host_key_checking: false
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      hosts:
        test-server: {}

  hosts:
    # Main test server - used for all recipes
    test-server:
      ansible_host: 10.10.10.198
      hostname: test-server.example.com
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      
      # Service-specific configs (when testing individual services)
      domain_name: test-server.example.com
      postgresql_version: "15"
      postgis_version: "3.3"
      database_port: 5433
      redis_memory_mb: 512
      redis_port: 6379
      webserver: gunicorn
      webserver_port: 8181