# Comprehensive Example Inventory
# Based on legacy Fabric configuration patterns
# Copy and customize for your environment

---
all:  
  vars:
    # === CONNECTION CONFIGURATIONS ===
    
    # Default connection (root with SSH keys - post-security)
    ansible_user: "{{ vault_ansible_user | default('root') }}"
    ansible_port: "{{ vault_ssh_port | default(22022) }}"
    ansible_host_key_checking: "{{ vault_ansible_host_key_checking | default(false) }}"
    ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file | default('~/.ssh/id_rsa') }}"
    ansible_ssh_common_args: "{{ vault_ansible_ssh_common_args | default('-o StrictHostKeyChecking=no') }}"
    
    # Global Settings (with vault fallbacks)
    git_user_full_name: "{{ vault_git_user_full_name | default('System Administrator') }}"
    git_user_email: "{{ vault_git_user_email | default('admin@example.com') }}"
    timezone: "{{ vault_timezone | default('America/New_York') }}"
    locale: "{{ vault_locale | default('en_US.UTF-8') }}"
    
  children:
    # === CONNECTION SWITCHING GROUPS ===
    
    # Security setup group - uses root with password for initial setup
    security_targets:
      vars:
        ansible_user: "{{ vault_ansible_user | default('root') }}"
        ansible_port: "{{ vault_initial_ssh_port | default(22022) }}"
        ansible_ssh_pass: "{{ vault_root_password }}"  # Required for initial setup, no default
        ansible_host_key_checking: "{{ vault_ansible_host_key_checking | default(false) }}"
        ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file | default('~/.ssh/id_rsa') }}"
        ansible_ssh_common_args: "{{ vault_ansible_ssh_common_args | default('-o StrictHostKeyChecking=no') }}"
      hosts:
        # Include all servers for security setup
        generic-prod: {}
        generic-staging: {}
        web-prod: {}
        web-staging: {}
        db-master: {}
        db-replica: {}
        cache-prod: {}
        lb-prod: {}
        vpn-prod: {}
    
    # Post-security group - uses admin with SSH keys for all operations  
    service_targets:
      vars:
        ansible_user: "{{ vault_ansible_user | default('root') }}"
        ansible_port: "{{ vault_ssh_port | default(22022) }}"
        ansible_host_key_checking: "{{ vault_ansible_host_key_checking | default(false) }}"
        ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file | default('~/.ssh/id_rsa') }}"
        ansible_ssh_common_args: "{{ vault_ansible_ssh_common_args | default('-o StrictHostKeyChecking=no') }}"
      hosts:
        # Include all servers for service operations
        generic-prod: {}
        generic-staging: {}
        web-prod: {}
        web-staging: {}
        db-master: {}
        db-replica: {}
        cache-prod: {}
        lb-prod: {}
        vpn-prod: {}
    
    # === SERVICE-SPECIFIC GROUPS ===
    
    # Generic Foundation Servers
    generic_servers:
      vars:
        admin_user: "{{ vault_admin_user | default('admin') }}"
        admin_password: "{{ vault_admin_password }}"  # Required, no default
        admin_groups: "admin,www-data"
        ssh_disable_root: true
        ssh_enable_password_auth: false
        python_version: "3.11"
        
      hosts:
        generic-prod:
          ansible_host: 10.0.1.10
          hostname: generic-prod.example.com
          
        generic-staging:
          ansible_host: 10.0.1.11
          hostname: generic-staging.example.com

    # Web Application Servers
    web_servers:
      vars:
        admin_user: "{{ vault_admin_user | default('admin') }}"
        admin_password: "{{ vault_admin_password }}"  # Required, no default
        admin_groups: "admin,www-data"
        webserver: gunicorn
        webserver_port: 8181
        python_version: "3.11"
        geo_ip_enabled: true
        
      hosts:
        web-prod:
          ansible_host: 10.0.2.10
          hostname: web-prod.example.com
          domain_name: app.example.com
          
        web-staging:
          ansible_host: 10.0.2.11
          hostname: web-staging.example.com
          domain_name: staging.example.com

    # Database Servers
    database_servers:
      vars:
        admin_user: "{{ vault_admin_user | default('admin') }}"
        admin_password: "{{ vault_admin_password }}"  # Required, no default
        admin_groups: "admin,www-data"
        postgresql_version: "15"
        postgis_version: "3.3"
        listen_address: "*"
        
      hosts:
        db-master:
          ansible_host: 10.0.3.10
          hostname: db-master.example.com
          database_port: 5432
          postgres_password: "{{ vault_postgres_password }}"  # Required, no default
          
        db-replica:
          ansible_host: 10.0.3.11
          hostname: db-replica.example.com
          database_port: 5432

    # Cache Servers  
    cache_servers:
      vars:
        admin_user: "{{ vault_admin_user | default('admin') }}"
        admin_password: "{{ vault_admin_password }}"  # Required, no default
        admin_groups: "admin,www-data"
        redis_memory: 512  # MB
        redis_interface: "0.0.0.0"
        
      hosts:
        cache-prod:
          ansible_host: 10.0.4.10
          hostname: cache-prod.example.com
          port: 6379
          password: "{{ vault_redis_password }}"  # Required, no default

    # VPN Servers
    vpn_servers:
      vars:
        admin_user: "{{ vault_admin_user | default('admin') }}"
        admin_password: "{{ vault_admin_password }}"  # Required, no default
        admin_groups: "admin,www-data,docker"
        
      hosts:
        vpn-server:
          ansible_host: 10.0.5.10
          hostname: vpn.example.com
          domain: vpn.example.com
          vpn_passphrase: "{{ vault_vpn_passphrase }}"  # Required, no default
          # Primary VPN (UDP, faster)
          primary_port: 1194
          primary_proto: udp
          # Secondary VPN (TCP, reliable through firewalls)  
          secondary_port: 443
          secondary_proto: tcp

    # Load Balancers
    load_balancers:
      vars:
        admin_user: "{{ vault_admin_user | default('admin') }}"
        admin_password: "{{ vault_admin_password }}"  # Required, no default
        admin_groups: "admin,www-data"
        
      hosts:
        lb-prod:
          ansible_host: 10.0.6.10
          hostname: lb-prod.example.com
          domain: app.example.com
          proto: https
          backends:
            - "10.0.2.10:8181"  # web-prod
            - "10.0.2.11:8181"  # web-staging
          ssl_cert_dir: "~/.ssh/certificates/"
          ssl_cert_email: "ssl@example.com"