# Granular Task: Add User
# Equivalent to: cloudy-old/sys/user.py::sys_user_add()
# Usage: ansible-playbook tasks/sys/user/add-user.yml -e "username=john"

---
- name: Validate username is not root
  fail:
    msg: "Cannot manage root user with this task"
  when: username == "root"

  
- name: Check if user exists
  command: "id {{ username }}"
  register: user_exists
  failed_when: false
  changed_when: false

- name: Kill existing processes for user (if force recreate)
  shell: "pkill -KILL -u {{ username }}"
  failed_when: false
  when: 
    - force_recreate | default(false) | bool
    - user_exists.rc == 0
  
- name: Remove existing user (if force recreate)
  user:
    name: "{{ username }}"
    state: absent
    remove: true
    force: true
  when: 
    - force_recreate | default(false) | bool
    - user_exists.rc == 0
  
- name: Add or update user {{ username }}
  user:
    name: "{{ username }}"
    shell: "{{ user_shell | default('/bin/bash') }}"
    create_home: "{{ user_create_home | default(true) }}"
    state: present
  register: user_add_result
  
- name: Display success message
  debug:
    msg: "✅ User successfully added: {{ username }}"
  when: user_add_result.changed