# Recipe: Core Server Setup
# Purpose: Basic server configuration - runs after security.yml on all servers
# Prerequisites: Must run core/security.yml first
# Usage: ansible-playbook playbooks/recipes/core/base.yml -i inventory/hosts.yml

---
- name: Core Server Setup
  hosts: service_targets
  gather_facts: true
  become: true
  
  vars:
    task_paths: "../../../tasks"
    # Base system configuration (configurable via inventory)
    setup_swap: false
          
  pre_tasks:
    # Ensure proper grunt connection
    - name: Validate grunt connection
      include_tasks: "{{ task_paths }}/sys/core/ensure-grunt-connection.yml"
          
  tasks:
    # System Initialization
    - name: Initialize system
      include_tasks: "{{ task_paths }}/sys/core/init.yml"
      tags: [system, init]
      
    # Hostname Configuration
    - name: Configure hostname
      include_tasks: "{{ task_paths }}/sys/core/hostname.yml"
      vars:
        target_hostname: "{{ hostname }}"
      tags: [system, hostname]
      
    # Git Configuration
    - name: Install git
      include_tasks: "{{ task_paths }}/sys/core/install-git.yml"
      tags: [system, git]
      
    - name: Configure git for root
      include_tasks: "{{ task_paths }}/sys/core/configure-git.yml"
      vars:
        target_user: root
        git_name: "{{ git_user_full_name }}"
        git_email: "{{ git_user_email }}"
      tags: [system, git]
      
    - name: Configure git for grunt user
      include_tasks: "{{ task_paths }}/sys/core/configure-git.yml"
      vars:
        target_user: "{{ grunt_user }}"
        git_name: "{{ git_user_full_name }}"
        git_email: "{{ git_user_email }}"
      tags: [users, grunt, git]
      
    # Firewall Setup (additional rules beyond SSH)
    - name: Secure server with firewall
      include_tasks: "{{ task_paths }}/sys/firewall/secure-server.yml"
      tags: [firewall, security]
      
    # System Configuration
    - name: Configure timezone
      include_tasks: "{{ task_paths }}/sys/timezone/configure.yml"
      tags: [system, timezone]
      
    - name: Configure swap
      include_tasks: "{{ task_paths }}/sys/swap/configure.yml"
      when: setup_swap | bool
      tags: [system, swap]
      
    # Security Hardening (additional packages)
    - name: Install security packages
      include_tasks: "{{ task_paths }}/sys/security/install-common.yml"
      when: setup_security | default(true) | bool
      tags: [security, packages]
      
    # Final Validation
    - name: Validate grunt user access and configuration
      include_tasks: "{{ task_paths }}/sys/core/validate-grunt-access.yml"
      vars:
        grunt_password: "{{ grunt_password }}"
      tags: [validation, grunt]
      
  post_tasks:
    - name: Display completion summary
      debug:
        msg: |
          🎉 ✅ CORE SERVER SETUP COMPLETED!
          
          📋 Configuration Summary:
             ├── Hostname: {{ hostname }}
             ├── Timezone: {{ timezone }}
             ├── Grunt User: {{ grunt_user }}
             ├── SSH Port: {{ ansible_port }}
             ├── Firewall: UFW enabled
             └── Git: Configured
          
          🚀 Core server foundation ready for service deployments!
          
          📚 Next Steps:
             • Deploy services: web-server.yml, database-server.yml, etc.
             • All services now use grunt user with sudo access