# Recipe: PostgreSQL + PostGIS Database Server Setup
# Based on: cloudy-old/srv/recipe_database_psql_gis.py
# Usage: ansible-playbook playbooks/recipes/database-postgis-server.yml -i inventory/hosts.yml

---
- name: PostgreSQL + PostGIS Database Server Setup Recipe
  hosts: service_targets
  gather_facts: true
  become: true
  
  vars:
    task_paths: "../../../tasks"
    # Database Configuration
    pg_version: "{{ postgresql_version | default('15') }}"
    pgis_version: "{{ postgis_version | default('') }}"
    db_port: "{{ database_port | default(5432) }}"
    setup_pgpool2: "{{ pgpool2 | default(false) }}"
    
    # Setup flags
    run_generic_setup: "{{ generic | default(true) }}"
    setup_firewall: true
    
  pre_tasks:
    # Ensure proper secure connection
    - name: Validate secure connection
      include_tasks: "{{ task_paths }}/sys/core/ensure-secure-connection.yml"
    
    - name: Display database server setup information
      debug:
        msg: |
          🚀 Starting PostgreSQL + PostGIS Database Server Setup
          Target: {{ inventory_hostname }} ({{ ansible_host }})
          PostgreSQL Version: {{ pg_version }}
          PostGIS Version: {{ 'Latest available' if pgis_version == '' else pgis_version }}
          Port: {{ db_port }}
          PgPool2: {{ 'Yes' if setup_pgpool2 else 'No' }}
          
  tasks:
    # Generic Server Setup - Include core foundation tasks
    - name: Initialize system
      include_tasks: "{{ task_paths }}/sys/core/init.yml"
      when: run_generic_setup | bool
      tags: [generic, foundation, init]
      
    - name: Update system packages
      include_tasks: "{{ task_paths }}/sys/core/update.yml"
      when: run_generic_setup | bool
      tags: [generic, foundation, update]
      
    - name: Install common utilities
      include_tasks: "{{ task_paths }}/sys/core/install-common.yml"
      when: run_generic_setup | bool
      tags: [generic, foundation, packages]
      
    - name: Install UFW firewall
      include_tasks: "{{ task_paths }}/sys/firewall/install.yml"
      when: run_generic_setup | bool
      tags: [generic, foundation, firewall]
      
    # PostgreSQL Installation
    - name: Install PostgreSQL server
      include_tasks: "{{ task_paths }}/db/postgresql/install.yml"
      vars:
        pg_version: "{{ pg_version }}"
      tags: [database, postgresql, install]
      
    # PostGIS Installation and Configuration
    - name: Install PostGIS
      include_tasks: "{{ task_paths }}/db/postgis/install.yml"
      vars:
        psql_version: "{{ pg_version }}"
        pgis_version: "{{ pgis_version }}"
      tags: [database, postgis, install]
      
    - name: Configure PostGIS template
      include_tasks: "{{ task_paths }}/db/postgis/configure.yml"
      vars:
        pg_version: "{{ pg_version }}"
        pgis_version: "{{ pgis_version }}"
        legacy: "{{ legacy_postgis | default(false) }}"
      tags: [database, postgis, configure]
      
    # PgPool2 Connection Pooling (Optional)
    - name: Install PgPool2
      include_tasks: "{{ task_paths }}/db/pgpool2/install.yml"
      when: setup_pgpool2 | bool
      tags: [database, pgpool2, install]
      
    - name: Configure PgPool2
      include_tasks: "{{ task_paths }}/db/pgpool2/configure.yml"
      vars:
        backend_host: "localhost"
        backend_port: "{{ db_port if db_port != 5432 else 5433 }}"
        pgpool_port: "5432"
      when: setup_pgpool2 | bool
      tags: [database, pgpool2, configure]
      
    - name: Configure PgPool2 backends
      include_tasks: "{{ task_paths }}/db/pgpool2/configure-backends.yml"
      vars:
        backend_host: "localhost"
        backend_port: "{{ db_port if db_port != 5432 else 5433 }}"
      when: setup_pgpool2 | bool
      tags: [database, pgpool2, backends]
      
    - name: Start PgPool2
      include_tasks: "{{ task_paths }}/db/pgpool2/start.yml"
      when: setup_pgpool2 | bool
      tags: [database, pgpool2, service]
      
    # Firewall Configuration
    - name: Allow PostgreSQL through firewall
      include_tasks: "{{ task_paths }}/sys/firewall/allow-postgresql.yml"
      when: setup_firewall | bool and not setup_pgpool2
      tags: [firewall, postgresql]
      
    - name: Allow PgPool2 through firewall
      include_tasks: "{{ task_paths }}/sys/firewall/allow-port.yml"
      vars:
        port: "5432"
        proto: tcp
      when: setup_firewall | bool and setup_pgpool2
      tags: [firewall, pgpool2]
      
    - name: Allow PostgreSQL backend through firewall (with PgPool2)
      include_tasks: "{{ task_paths }}/sys/firewall/allow-port.yml"
      vars:
        port: "{{ db_port if db_port != 5432 else 5433 }}"
        proto: tcp
      when: setup_firewall | bool and setup_pgpool2 and (db_port != 5432 or setup_pgpool2)
      tags: [firewall, postgresql-backend]
      
      
  post_tasks:
    - name: Display database server completion summary
      debug:
        msg: |
          🎉 ✅ POSTGRESQL + POSTGIS DATABASE SERVER SETUP COMPLETED SUCCESSFULLY!
          📋 Configuration Summary:
             ├── PostgreSQL Version: {{ pg_version }}
             ├── PostGIS Version: {{ pgis_version if pgis_version != '' else 'Latest available' }}
             ├── Template Database: template_postgis (ready for spatial databases)
             ├── Connection Pooling: {{ 'PgPool2 enabled on port 5432' if setup_pgpool2 else 'Direct PostgreSQL connection' }}
             ├── Backend Port: {{ db_port if not setup_pgpool2 else (db_port if db_port != 5432 else 5433) }}
             ├── Firewall: {{ 'Database ports allowed' if setup_firewall else 'Not configured' }}
             └── Status: Ready for spatial database applications
          
          🚀 PostgreSQL + PostGIS database server is ready!
          
          📖 Connection Information:
          - Host: {{ ansible_host }}
          - Port: {{ '5432 (PgPool2) → ' + (db_port|string if db_port != 5432 else '5433') + ' (PostgreSQL)' if setup_pgpool2 else db_port }}
          - Template: template_postgis (for new spatial databases)
          
          📖 Next Steps:
          1. Create spatial databases: 
             createdb -T template_postgis mydatabase
          2. Create database users and set permissions
          3. Configure client applications to connect
          4. Set up backup and monitoring
          
  handlers:
    - name: restart pgpool2
      service:
        name: pgpool2
        state: restarted