---
# cloudy/tasks/web/nginx/setup-letsencrypt.yml
# Setup Let's Encrypt SSL certificates

- name: Install certbot and nginx plugin
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present
    update_cache: yes

- name: Create webroot directory for ACME challenges
  file:
    path: /var/www/letsencrypt
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Check if certificate already exists
  stat:
    path: "/etc/letsencrypt/live/{{ le_domain }}/fullchain.pem"
  register: cert_exists

- name: Obtain Let's Encrypt certificate
  command: |
    certbot certonly --nginx 
    --non-interactive 
    --agree-tos 
    --email {{ le_email }} 
    --domains {{ le_domain }}
    {% if le_staging | default(false) %}--staging{% endif %}
  when: not cert_exists.stat.exists
  register: certbot_result

- name: Update Nginx configuration to use Let's Encrypt certificate
  replace:
    path: "/etc/nginx/sites-available/{{ le_domain }}.conf"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - regexp: 'ssl_certificate\s+.*\.crt;'
      replace: 'ssl_certificate /etc/letsencrypt/live/{{ le_domain }}/fullchain.pem;'
    - regexp: 'ssl_certificate_key\s+.*\.key;'
      replace: 'ssl_certificate_key /etc/letsencrypt/live/{{ le_domain }}/privkey.pem;'
  when: certbot_result is succeeded
  notify: reload nginx

- name: Add trusted certificate for OCSP stapling
  lineinfile:
    path: "/etc/nginx/sites-available/{{ le_domain }}.conf"
    insertafter: 'ssl_certificate_key'
    line: '    ssl_trusted_certificate /etc/letsencrypt/live/{{ le_domain }}/chain.pem;'
  when: certbot_result is succeeded
  notify: reload nginx

- name: Setup auto-renewal cron job
  cron:
    name: "Let's Encrypt renewal"
    job: "/usr/bin/certbot renew --quiet --post-hook 'systemctl reload nginx'"
    hour: "3"
    minute: "30"
    weekday: "1,4"  # Monday and Thursday
    user: root

- name: Test certificate renewal
  command: certbot renew --dry-run
  register: renewal_test
  changed_when: false
  failed_when: false

- name: Display Let's Encrypt status
  debug:
    msg: |
      Let's Encrypt SSL Certificate:
      {% if certbot_result is succeeded %}
      ✓ Certificate obtained successfully for {{ le_domain }}
      ✓ Auto-renewal configured (Mon & Thu at 3:30 AM)
      {% if renewal_test.rc == 0 %}
      ✓ Renewal test passed
      {% else %}
      ⚠ Renewal test failed - check configuration
      {% endif %}
      {% else %}
      ⚠ Using existing certificate at /etc/letsencrypt/live/{{ le_domain }}/
      {% endif %}