# Ansible Vault - Encrypted Credentials
# This file contains sensitive credentials and should be encrypted with ansible-vault
# 
# To encrypt this file, run:
# ansible-vault encrypt cloudy/inventory/group_vars/vault.yml
#
# To edit encrypted vault, run:
# ansible-vault edit cloudy/inventory/group_vars/vault.yml

# IMPORTANT: Replace these example values with your actual secure credentials
# before encrypting the vault file

# === AUTHENTICATION CREDENTIALS ===

# Root User Password (ONLY for initial security setup)
vault_root_password: "pass4now"

# Admin User Password (for account creation and sudo only)
vault_admin_password: "pass4now"

# === CONNECTION CONFIGURATION ===

# Admin user account name
vault_admin_user: "admin"

# Secure SSH port
vault_ssh_port: 22

# === GLOBAL SERVER CONFIGURATION ===

# Git configuration for server operations
vault_git_user_full_name: "Dev User"
vault_git_user_email: "dev@example.com"

# Server locale and timezone settings
vault_timezone: "America/New_York"
vault_locale: "en_US.UTF-8"

# Database Credentials
vault_postgres_password: "pass4now"
vault_mysql_root_password: "pass4now"

# Cache Credentials
vault_redis_password: "pass4now"

# VPN Credentials
vault_vpn_passphrase: "pass4now"


