# Production Vault Template - ENCRYPT BEFORE USE!
# 
# To create your production vault:
# 1. Copy this file to production.yml
# 2. Replace all template values with real production credentials
# 3. Encrypt: ansible-vault encrypt .secrets/production.yml
#
# CRITICAL: Use strong, unique passwords for production!

# === AUTHENTICATION CREDENTIALS ===

# Root User Password (ONLY for initial security setup)
vault_root_password: "REPLACE_WITH_SECURE_ROOT_PASSWORD"

# Admin User Password (for account creation and sudo only)
vault_admin_password: "REPLACE_WITH_SECURE_ADMIN_PASSWORD"

# === CONNECTION CONFIGURATION ===

# Admin user account name (standard: admin)
vault_admin_user: "admin"

# Secure SSH port (standard: 222)
vault_ssh_port: 222

# === GLOBAL SERVER CONFIGURATION ===

# Git configuration for server operations
vault_git_user_full_name: "Production Admin"
vault_git_user_email: "admin@yourcompany.com"

# Server locale and timezone settings
vault_timezone: "America/New_York"
vault_locale: "en_US.UTF-8"

# === SERVICE CREDENTIALS ===

# Database Credentials
vault_postgres_password: "REPLACE_WITH_SECURE_POSTGRES_PASSWORD"
vault_mysql_root_password: "REPLACE_WITH_SECURE_MYSQL_PASSWORD"

# Cache Credentials
vault_redis_password: "REPLACE_WITH_SECURE_REDIS_PASSWORD"

# VPN Credentials
vault_vpn_passphrase: "REPLACE_WITH_SECURE_VPN_PASSPHRASE"