# Task: Configure PgPool-II Backend Servers
# Purpose: Setup PostgreSQL backend connections for pgpool2
# Supports multiple backends for load balancing (future enhancement)

---
- name: Configure primary backend server
  lineinfile:
    path: /etc/pgpool2/pgpool.conf
    regexp: "^{{ item.param }} ="
    line: "{{ item.param }} = {{ item.value }}"
  loop:
    - { param: "backend_hostname0", value: "'{{ backend_host | default('localhost') }}'" }
    - { param: "backend_port0", value: "{{ backend_port | default(5433) }}" }
    - { param: "backend_weight0", value: "1" }
    - { param: "backend_flag0", value: "'ALLOW_TO_FAILOVER'" }
  notify: restart pgpool2

- name: Configure backend connection settings
  lineinfile:
    path: /etc/pgpool2/pgpool.conf
    regexp: "^{{ item.param }} ="
    line: "{{ item.param }} = {{ item.value }}"
  loop:
    - { param: "backend_connection_cache", value: "on" }
    - { param: "reset_query_list", value: "'ABORT; DISCARD ALL'" }
  notify: restart pgpool2

- name: Create pgpool_passwd file for MD5 authentication
  file:
    path: /etc/pgpool2/pool_passwd
    state: touch
    owner: postgres
    group: postgres
    mode: '0600'
  when: pgpool_enable_pool_passwd | default(false)

- name: Display backend configuration
  debug:
    msg: |
      ✅ Backend configured:
      Primary: {{ backend_host | default('localhost') }}:{{ backend_port | default(5433) }}
      Connection cache: Enabled
      Failover: Allowed