# Granular Task: Install UFW Firewall (Smart Installation)
# Equivalent to: cloudy-old/sys/firewall.py::fw_install()
# Usage: include_tasks: install.yml

---
- name: Check if UFW is already installed
  command: dpkg -l ufw
  register: ufw_check
  failed_when: false
  changed_when: false
  
- name: Get UFW status if installed
  command: ufw status
  register: ufw_status
  failed_when: false
  changed_when: false
  when: ufw_check.rc == 0
  
- name: Install UFW firewall (only if not installed)
  apt:
    name: ufw
    state: present
    update_cache: true
  register: ufw_installation
  when: ufw_check.rc != 0
  
- name: Display UFW installation status
  debug:
    msg: |
      ✅ UFW firewall ready
      Status: {{ 'Fresh installation' if ufw_installation.changed else 'Already installed' }}
      Current Status: {{ ufw_status.stdout if ufw_check.rc == 0 else 'Not yet configured' }}
      ⚠️  Use firewall configuration tasks to enable and configure rules