---
- name: Database Server Setup
  hosts: databases
  become: true
  gather_facts: true
  
  pre_tasks:
    - name: Include baseline configuration
      ansible.builtin.include: server-baseline.yml
  
  roles:
    - role: services/postgresql
    - role: applications/backup
      vars:
        backup_type: postgresql
    - role: security/firewall
      vars:
        firewall_rules:
          - { port: 5432, protocol: tcp, rule: allow, src: "{{ database_allowed_hosts | default(['10.0.0.0/8']) }}" }
          - { port: "{{ ssh_port | default(22) }}", protocol: tcp, rule: allow }
  
  tags: [database, postgresql, backup]